# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' @noRd
import_multiple_excel <- function(file_paths) {
  result <- list()

  for (file in file_paths) {
    if (file.exists(file)) {
      message(paste("Reading:", file))
      tryCatch({
        data <- read_excel(file)
        result[[file]] <- data  # Store in list with filename as key
      }, error = function(e) {
        warning(paste("Error reading", file, ":", e$message))
      })
    } else {
      warning(paste("File does not exist:", file))
    }
  }

  return(result)
}

